### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by vinigfer** [leandrotoledo/legendas-tv-api#1]
Quando tentei utilizar esse script para baixar algumas legendas do legendas.tv, estou recebendo o erro indicado. Os passos que executei foram os seguintes:

1) Baixei o arquivo e renomeei ele para legendas.py
2) Abri um terminal python
3) Executei o seguinte código:

```
from legendas import *
legendas_tv = LegendasTV("meu_login", "minha_senha")
legendas_tv.search("The Big Bang Theory")
```

4) Recebi o erro abaixo:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "legendas.py", line 111, in search
    legendas = self._parser(r.text)
  File "legendas.py", line 84, in _parser
    results = html.find(id='conteudodest').findAll('span') # TODO: Pagination
AttributeError: 'NoneType' object has no attribute 'findAll'
```

Isso é por conta da estrutura html do site ter mudado? Este projeto está funcionando?

**Comment by leandrotoledo** [comment]
Olá @vinigfer, essa biblioteca tinha sido desenvolvida para a versão anterior do site do legendas.tv. Desde a mudança no site é improvavél que continue funcionando. Se não achar uma nova como alternativa podemos tentar readaptar esta.

Abraços.
